### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by davelab6** [GoogleCloudPlatform/woolaroo-language-learning-app#121]
What license is this project available under?

**Comment by arecvlohe** [comment]
I am also wondering what license this project is under. In the blog post about it, it states:

> Woolaroo is open source and allows language communities like ours to preserve and expand their language word lists and add audio recordings to help with pronunciation.

I don't think this code is open source unless a license states as such. My only other opinion is I think it should be released under MIT License so that other communities can use it for their own needs.
