### ISSUE TITLE
Issues building the project

### ISSUE THREAD

**Issue by PGrad** [GoogleCloudPlatform/woolaroo-language-learning-app#134]
I found out about this project through the Google homepage, and thought it sounded like a cool project. I tried to build it locally but I'm running into quite a few problems.

First of all, I had to be careful with the version of node I used to build the project. This project uses a version of node-sass which cannot be built with Node 16, as the package just [recently added support](https://github.com/sass/node-sass/issues/3077). So I had to use the Node LTS 14.17.0. Not a big deal.

I changed the src/config.json to use my firebase project and successfully did `npm run build` and `firebase deploy`. I had to change the `engines` field in functions/package.json to "14" before I could successfully deploy though. However, when I do `npm run start` I find that Woolaroo is still using some "barnard-project" firebase project which I don't have permissions to use. I see references to this project littered through the code, so... I suppose I need to change more files than src/config.json to be able to use my firebase project? At this point I just see the Woolaroo web page on localhost, and then when I sign in through my google account I get a page saying "Interested to join us?". How do I get the Woolaroo app to use my firebase project?

I also found that the documentation for running firebase functions locally was wrong: there is no `serve_functions` field in functions/package.json, there is only a `serve` field. I suppose I could update the README.md but I see there's 17 open PRs going back to February and the last submission is from March 22nd. The issues are unresolved too; I'm not sure if anyone is maintaining this repo.

Is this just a tech demo which is not expected to be used seriously? Is there any expectation that this will be maintained in the future?

E: also sorry for having a bit of an attitude, I felt low-key angry when I couldn't get this project to work.

**Comment by lyleaf** [comment]
Sorry about the confusion. You were using a wrong branch, now we've updated the main branch to the right one feature/multilanguage 
You can take it and create the web app. @aaronneugebauer @AaronNeugebauerRush Anything else they need to be aware of?

**Comment by AaronNeugebauerRush** [comment]
I think that should be it. Hopefully the readme should explain everything.

Aaron
