### ISSUE TITLE
How to add the Pueblo Tiwa language to Woolaroo

### ISSUE THREAD

**Issue by b3ccio** [GoogleCloudPlatform/woolaroo-language-learning-app#203]
Hi, we'd like to use your app and help save the Pueblo Tiwa language. How can we get started? Thanks!

**Comment by justingrayston** [comment]
Sure - leave it with me - I will find the best email address to give you.

**Comment by justingrayston** [comment]
Hey @b3ccio please reach out to woolaroo@google.com

Thanks
